### ISSUE TITLE
New(?) Device: GT-I9500

### ISSUE THREAD

**Issue by tapicer** [Benjamin-Dobell/Heimdall#141]
I'm using the latest version on Mac to flash a recovery to a Galaxy S4 (i9500) and it's failing (same thing happens on Linux). See below the commands I run. I've tried on several machines and with several images, it always fails. I can provide more info if needed.

```
Jonathans-MacBook-Pro:CF-Auto-Root-ja3g-ja3gxx-gti9500 tapicer$ heimdall flash --recovery CF-Auto-Root-ja3g-ja3gxx-gti9500.tar.md5 --verbose
Heimdall v1.4.0

Copyright (c) 2010-2013, Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
      Manufacturer: "SAMSUNG"
           Product: "Gadget Serial"

            length: 18
      device class: 2
               S/N: 0
           VID:PID: 04E8:685D
         bcdDevice: 021B
   iMan:iProd:iSer: 1:2:0
          nb confs: 1

interface[0].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 83
           max packet size: 0010
          polling interval: 09

interface[1].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 02
           max packet size: 0200
          polling interval: 00
Claiming interface...
Setting up interface...

Initialising protocol...
WARNING: Control transfer #2 failed. Result: -7
WARNING: Control transfer #3 failed. Result: -7
WARNING: Control transfer #4 failed. Result: -7
WARNING: Control transfer #5 failed. Result: -7
WARNING: Control transfer #6 failed. Result: -1
ERROR: Failed to send data: "ODIN"
Releasing device interface...
```

**Comment by gandalfk7** [comment]
I have the same problem with a SM-T520, on 2 different linux (ubuntu 12.04 and 14.04) machines and a windows 7 machine:
my output (on a linux, ubuntu 12.04) is: 

    heimdall flash --RECOVERY ./recovery.img --no-reboot --verbose
    Heimdall v1.4.0
    Copyright (c) 2010-2013, Benjamin Dobell, Glass Echidna
    http://www.glassechidna.com.au/
    This software is provided free of charge. Copying and redistribution is encouraged.
    If you appreciate this software and you would like to support future development please consider donating:
    http://www.glassechidna.com.au/donate/

    Initialising connection...
    Detecting device...
      Manufacturer: "SAMSUNG"
           Product: "Gadget Serial"

            length: 18
      device class: 2
               S/N: 0
           VID:PID: 04E8:685D
         bcdDevice: 021B
    iMan:iProd:iSer: 1:2:0
          nb confs: 1

    interface[0].altsetting[0]: num endpoints = 1
    Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 83
           max packet size: 0010
          polling interval: 09

    interface[1].altsetting[0]: num endpoints = 2
    Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 02
           max packet size: 0200
          polling interval: 00
    Claiming interface...
    Attempt failed. Detaching driver...
    Claiming interface again...
    Setting up interface...

    Initialising protocol...
    WARNING: Control transfer #2 failed. Result: -7
    WARNING: Control transfer #3 failed. Result: -7
    WARNING: Control transfer #4 failed. Result: -7
    WARNING: Control transfer #5 failed. Result: -7
    WARNING: Control transfer #6 failed. Result: -99
    ERROR: Failed to send data: "ODIN"
    Releasing device interface...
    Re-attaching kernel driver...

**Comment by aol-nnov** [comment]
+1 for this!

I have samsung I9500 non-LTE international
```
sudo heimdall flash --RECOVERY ./recovery-clockwork-6.0.3.2-i9500.img --no-reboot --verbose
Heimdall v1.4.0

Copyright (c) 2010-2013, Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
      Manufacturer: "SAMSUNG"
           Product: "Gadget Serial"

            length: 18
      device class: 2
               S/N: 0
           VID:PID: 04E8:685D
         bcdDevice: 021B
   iMan:iProd:iSer: 1:2:0
          nb confs: 1

interface[0].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 83
           max packet size: 0010
          polling interval: 09

interface[1].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 02
           max packet size: 0200
          polling interval: 00
Claiming interface...
Setting up interface...

Initialising protocol...
WARNING: Control transfer #2 failed. Result: -7
WARNING: Control transfer #3 failed. Result: -7
WARNING: Control transfer #4 failed. Result: -7
WARNING: Control transfer #5 failed. Result: -7
WARNING: Control transfer #6 failed. Result: -1
ERROR: Failed to send data: "ODIN"
Releasing device interface...
```
same behaviour on linux and mac.

**Comment by j-woodlee** [comment]
Any updates on this problem?  Galaxy Tab Pro 10.1 on Mac OSX 10.10.1 and getting this: 

```
heimdall flash --RECOVERY recovery.img --no-reboot --verbose
Heimdall v1.4.0

Copyright (c) 2010-2013, Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
      Manufacturer: "SAMSUNG"
           Product: "Gadget Serial"

            length: 18
      device class: 2
               S/N: 0
           VID:PID: 04E8:685D
         bcdDevice: 021B
   iMan:iProd:iSer: 1:2:0
          nb confs: 1

interface[0].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 83
           max packet size: 0010
          polling interval: 09

interface[1].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 02
           max packet size: 0200
          polling interval: 00
Claiming interface...
Setting up interface...

Initialising protocol...
WARNING: Control transfer #2 failed. Result: -7
WARNING: Control transfer #3 failed. Result: -7
WARNING: Control transfer #4 failed. Result: -7
WARNING: Control transfer #5 failed. Result: -7
WARNING: Control transfer #6 failed. Result: -1
ERROR: Failed to send data: "ODIN"
Releasing device interface...
```

Any help is appreciated :)

**Comment by apsabelhaus** [comment]
Bump. Getting almost the exact same error as @j-woodlee, with the following minor difference at the end. Ubuntu 14.04.1, kernel 3.14.1. Samsung Galaxy Tab Pro 10.1, SM-T520.

Claiming interface...
Attempt failed. Detaching driver...
Claiming interface again...
Setting up interface...

Initialising protocol...
WARNING: Control transfer #2 failed. Result: -7
WARNING: Control transfer #3 failed. Result: -7
WARNING: Control transfer #4 failed. Result: -7
WARNING: Control transfer #5 failed. Result: -7
WARNING: Control transfer #6 failed. Result: -1
ERROR: Failed to receive handshake response. Retrying...
ERROR: Failed to send data: "ODIN"
Releasing device interface...
Re-attaching kernel driver...

thanks all!

**Comment by Benjamin-Dobell** [comment]
Please try build the latest version from source, the issue should be resolved.

**Comment by apsabelhaus** [comment]
Hi Benjamin! Thanks for the tip about building from this repo. Unfortunately, it still doesn't seem to flash the device. Here's the full output from the build of heimdall as of this evening: 

drew@heidi-linux:~/repositories/Heimdall/bin$ sudo ./heimdall flash --verbose --RECOVERY clockworkmodrecovery6051picassowifi.img --no-reboot
Heimdall v1.4.1

Copyright (c) 2010-2014 Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
      Manufacturer: "SAMSUNG"
           Product: "Gadget Serial"

            length: 18
      device class: 2
               S/N: 0
           VID:PID: 04E8:685D
         bcdDevice: 021B
   iMan:iProd:iSer: 1:2:0
          nb confs: 1

interface[0].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 83
           max packet size: 0010
          polling interval: 09

interface[1].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 02
           max packet size: 0200
          polling interval: 00
Claiming interface...
Attempt failed. Detaching driver...
Claiming interface again...
Setting up interface...

Initialising protocol...
ERROR: Failed to receive handshake response. Result: -7
ERROR: Protocol initialisation failed!

Releasing device interface...
Re-attaching kernel driver...

drew@heidi-linux:~/repositories/Heimdall/bin$ 

Can you think of anything I might need to check that might be causing this? Or would it still be a genuine bug? I've got the ubuntu packages for libusb-1.0.0 and its -dev and -dbg versions installed, but from what I understand, the -7 error is related to libusb. I'm happy to help debug however I can!

**Comment by kriswebdev** [comment]
heimdall print-pit working after building from last (today) source!

Quick instructions for the lazy ones:
git clone https://github.com/Benjamin-Dobell/Heimdall.git
cd heimdall
sudo apt-get install build-essential cmake zlib1g-dev qt5-default libusb-1.0-0-dev libgl1-mesa-glx libgl1-mesa-dev
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
cd bin
./heimdall print-pit --no-reboot

Just need to reboot the phone in download mode before issuing further heimdall commands.

**Comment by kynan** [comment]
@apsabelhaus  @kriswebdev Your's might be the same issue as #228. Try my fix with the udev rule.
